/**
 * Web re-export of the canonical print-settings module.
 */
export {
  PRINT_SETTINGS_VERSION,
  DEFAULT_PRINT_SETTINGS_V1,
  NORMAL_A4_MARGIN_PT,
  BRIGHTNESS_MIN,
  BRIGHTNESS_MAX,
  BRIGHTNESS_STEP,
  CONTENT_SCALE_MIN,
  CONTENT_SCALE_MAX,
  CONTENT_SCALE_STEP,
  buildPrintSettingsV1,
  buildDefaultPrintSettingsV1,
  resolvePrintSettings,
  shouldUseLegacyPrintBehavior,
  planJobPrint,
  isValidPageRange,
  normalizeBrightnessPercent,
  normalizeContentScalePercent,
  hasPrintContentAdjustments,
  type PrintSettingsV1,
  type PrintOrientationV1,
  type PrintPaperSizeV1,
  type PrintScaleV1,
  type PrintMarginsV1,
  type PrintBrightnessPercent,
  type PrintContentScalePercent,
  type ResolvedPrintSettings,
  type ResolvePrintSettingsOptions,
  type JobPrintPlan,
} from "../shared/print-settings";
